default: &default
  adapter: postgresql
  encoding: unicode
  username: wendellopes
  password: w2n1b1b2
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: talent_notes_development

test:
  <<: *default
  database: talent_notes_test

production:
  <<: *default
  database: talent_notes_production
  username: talent_notes
  password: <%= ENV['TALENT_NOTES_DATABASE_PASSWORD'] %>
